; This file has to be in the root of your Vscode folder
[mypy]
plugins = ["mypy_django_plugin.main"]

[django-stubs]
django_settings_module = "src.myproject.settings"

python_version = 3.12

check_untyped_defs = True
; disallow_any_generics = True
; disallow_untyped_calls = True
; disallow_untyped_decorators = True
; ignore_errors = False
; ignore_missing_imports = True
; implicit_reexport = False
; strict_optional = True
; strict_equality = True
; no_implicit_optional = True
; warn_unused_ignores = True
; warn_redundant_casts = True
; warn_unused_configs = True
; warn_unreachable = True
; warn_no_return = True
; ignore_missing_imports = True
; plugins = sqlmypy